language: ruby
rvm:
  - 1.9.3
  - 2.0.0
env:
  - "RAILS_VERSION=3.2"
  - "RAILS_VERSION=4.2.3"
before_script:
  - bundle install
script:
  - RAILS_ENV=test bundle exec rake test
notifications:
  slack:
    secure: HLqJ/tpULR8KFab3LK9IVDjDwvz98+7V3W45/qu9XedR22mzG02TkIXbPAjTcFudCVwULVhAefAqvq3/HbOwcvcs1T+Wtz7E3rn7NjvcdeeAea63Tz5exujz5csJNuTOecIShSWE9yL+Owm2thAluZaWmDSdsbUNWODy1wmR8VLainXxZUFboZknw+wAZ/cTn8+ns0J/lpPJzmql2tUT8RET1Oav9nfUC5Necy7e96iwKjvdDZF69V5shD1/dW6IZ+ZypN3vMzdo0OmcMITSENCEF/Uee5uPROjLjveGlP2fietq5mdLRor9E6lulOG6D9lRJi0m25XudMomUZD9g0V02zTw4FqGuuPLpZuY4qgKh0wxtkAM7E/M+ktC4rcLDu/0WgDpb0eLDRwKBxrQVLEvZi8dHWzqyXmvwt4hq4IkyGbvomb+prbPV7vcY6O/J0q2wf8PdK4MvhIHXZ9Up5sMNDUxUl1vIWc6KvK5XCEfTQimJepG8TFZSJgiun7i+Os3DMEcoSNuy15/pQvUT/hvGlacTeQvdnvqAt4I2Z3fse0qoF5g/b4l5NSJsrlLn51Xai5QZ0kUvN9lXg7U6t6lof5Iqvo4SUZcKyvsvC7ManPCKKIiU3F7BwyZ/AMFa4qGhOyRr6OV13yLsWsZzM+PIfjK13Lterj0PxQDG50=
